#!bin/bash

# Making the default permissions for every new file/folder to be 660/770
umask 007

# Creating Virus user 'corona'
useradd --create-home corona

# Allowing citizens to read the contents of Virus
chmod 774 -R /home/corona

# Creating accounts for doctors
useradd --create-home doc1
useradd --create-home doc2

adduser corona doc1
adduser corona doc2

counter=1

# Looping and creating patients and adding them to their respective groups
while [ $counter -le 5 ]
do
    useradd --create-home doc1_pat$counter
    useradd --create-home doc2_pat$counter

    adduser corona doc1_pat$counter
    adduser corona doc2_pat$counter
    adduser doc1 doc1_pat$counter
    adduser doc2 doc2_pat$counter
    ((counter++))
done

echo "All accounts created!"

# Making required directories
mkdir -p /home/doc1/{Symptoms,Vaccines,Requests}
mkdir -p /home/doc2/{Symptoms,Vaccines,Requests}

counter=1

while [ $counter -le 5 ]
do
    mkdir -p /home/doc1_pat$counter/Symptoms
    mkdir -p /home/doc2_pat$counter/Symptoms
    ((counter++))
done

echo "Required directories made!"
    
# Changing the permissions of the Vaccines directories
chmod 774 -R /home/doc1/Vaccines
chmod 774 -R /home/doc2/Vaccines

# Making vaccine files in Vaccines directories
touch /home/doc1/{covax,sputnik,corin,coron,cona}
touch /home/doc2/{covax,sputnik,corin,coron,cona}

echo covax > /home/doc1/covax
echo sputnik > /home/doc1/sputnik
echo corin > /home/doc1/corin
echo coron > /home/doc1/coron
echo cona > /home/doc1/cona

echo covax > /home/doc2/covax
echo sputnik > /home/doc2/sputnik
echo corin > /home/doc2/corin
echo coron > /home/doc2/coron
echo cona > /home/doc2/cona

# Making request files
touch /home/doc1/Requests/{p1,p2,p3,p4,p5}
touch /home/doc2/Requests/{p1,p2,p3,p4,p5}

counter=1

while [ $counter -le 5 ]
do
    chown doc1_pat$counter /home/doc1/Requests/p$counter
    chown doc2_pat$counter /home/doc2/Requests/p$counter
    ((counter++))
done

